<a href="https://colab.research.google.com/github/jaykumar3498/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
ages = [10, 5, 8, 32, 65, 43]
print(ages)

[10, 5, 8, 32, 65, 43]


In [5]:
age = np.array(ages)
print(type(age))
print(age)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [14]:
print(age)
print("Size =" , age.size)
print("Shape =", age.shape)

[10  5  8 32 65 43]
Size = 6
Shape = (6,)


In [9]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [10]:
weights = [32, 18, 26, 60, 55, 65]

In [12]:
people = np.array([ages,weights])
print(type(people))
print(people)

<class 'numpy.ndarray'>
[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


In [15]:
print("Size =" , people.size)
print("Shape =", people.shape)

Size = 12
Shape = (2, 6)


In [16]:
people = people.reshape(12,1)
print(people)
print(people.size)
print(people.shape)

[[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]
12
(12, 1)


In [17]:
#Exercise
ar = np.array([7, 9, 65, 33, 85, 99])
ar

array([ 7,  9, 65, 33, 85, 99])

In [18]:
mat = np.array([1,2,4,2,3,0,0,5,1])
mat

array([1, 2, 4, 2, 3, 0, 0, 5, 1])

In [20]:
mat = mat.reshape(3,3)
mat

array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1]])

In [21]:
mat = mat.reshape(9,1)
mat

array([[1],
       [2],
       [4],
       [2],
       [3],
       [0],
       [0],
       [5],
       [1]])

In [22]:
fiv = np.arange(0, 55, 5)
fiv

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
fiv2 = np.linspace(0,50,11)
fiv2

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [25]:
two = np.repeat(2, 10)
print(two)

[2 2 2 2 2 2 2 2 2 2]


In [31]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
print("1:", 2 * fiv)
print("2:", 10 + fiv)
print("3:", fiv - 1)
print("4:", fiv/5)
print("5:", fiv **2)
print("6:", fiv < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


In [33]:
fives = list(range(0,5001,5))
fives

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [64]:
people.shape = (2, 6)
print(people, "\n")
print(people.transpose())

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]] 

[[10 32]
 [ 5 18]
 [ 8 26]
 [32 60]
 [65 55]
 [43 65]]


In [39]:
people.dtype

dtype('int64')

In [40]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [43]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '2'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65,  2], dtype=int32)

In [44]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[10  5  8 32 65  2]


In [45]:
ages_with_strings.size

6

In [46]:
ages_with_strings.size/21

0.2857142857142857

In [47]:
np.array([10, 5, 8, '32', '65', '43']).size

6

In [48]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


In [70]:
#Exercise
s = np.array(['3','5','10','20','54','30'],dtype='float')
print(s)
print(s.shape)

[ 3.  5. 10. 20. 54. 30.]
(6,)


In [71]:
print(s.transpose())
print(s.size)
print(s.shape)

[ 3.  5. 10. 20. 54. 30.]
6
(6,)


In [74]:
s = np.array([['3','5','10','20','54','30']],dtype='float')
print(s)
print(s.shape)

[[ 3.  5. 10. 20. 54. 30.]]
(1, 6)


In [75]:
print(s.transpose())
print(s.size)
print(s.shape)

[[ 3.]
 [ 5.]
 [10.]
 [20.]
 [54.]
 [30.]]
6
(1, 6)


In [66]:
s.astype('bool')

array([ True,  True,  True,  True,  True,  True])

In [77]:
fiv[0]

0

In [78]:
fiv[2:]

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [79]:
fiv[-1]

50

In [83]:
print(people)
people[:3, :4]

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


array([[10,  5,  8, 32],
       [32, 18, 26, 60]])

In [85]:
#Exercise
arr = np.zeros(50,dtype='int32')
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)

In [86]:
rep = np.repeat(2,50)
rep

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [89]:
arr2 = np.arange(0,2*np.pi,0.1)
arr2

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [91]:
arr2[0:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

In [93]:
arr2[-4:-1]

array([5.9, 6. , 6.1])

In [97]:
arr2[4:8]

array([0.4, 0.5, 0.6, 0.7])

In [98]:
fiv

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [99]:
np.flip(fiv)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [100]:
rev = np.flip(fiv)
rev

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [104]:
rev = fiv[-1::-1]
rev

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [108]:
arr = np.flip(fiv2)
arr

array([50., 45., 40., 35., 30., 25., 20., 15., 10.,  5.,  0.])

In [110]:
arr = fiv2[::4]
arr

array([ 0., 20., 40.])

In [112]:
arr = fiv2[-1::-2]
arr

array([50., 40., 30., 20., 10.,  0.])

In [113]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [115]:
nums = np.arange(0, 4, 0.2555)
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

In [120]:
print(np.min(nums).round(2))
print(np.max(nums).round(2))
print(np.sum(nums).round(2))
print(np.mean(nums).round(2))
print(np.median(nums).round(2))
print(np.var(nums).round(2))
print(np.std(nums).round(2))

0.0
3.83
30.66
1.92
1.92
1.39
1.18


In [133]:
coin = np.random.choice([1,0],10)
coin

array([0, 0, 1, 1, 1, 0, 1, 1, 0, 1])

In [140]:
np.random.rand(3,1,2)

array([[[0.7330349 , 0.12919395]],

       [[0.05573156, 0.57458558]],

       [[0.97828634, 0.65449282]]])

In [142]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
s

array([ 0.08267764, -0.18769165, -0.07807348,  0.13565756,  0.2340373 ,
       -0.01308337,  0.09504078, -0.1459796 ,  0.03403565, -0.08320217,
        0.00827025, -0.08990487,  0.08824773, -0.09359958, -0.15498729,
       -0.1602613 , -0.06063384, -0.05171962,  0.08604064, -0.02706252,
        0.05437041,  0.08141572, -0.03749433,  0.07442102, -0.03344591,
        0.0858766 , -0.11571809,  0.12160357, -0.20432663,  0.03079853,
        0.13735782,  0.01834043, -0.09628594, -0.07409502,  0.13774933,
       -0.02736016,  0.01461306, -0.03035578,  0.07170887, -0.27520224,
        0.02925686,  0.05667848,  0.14693529,  0.08756552, -0.10645263,
       -0.04047674,  0.14089889, -0.00726436, -0.01586487, -0.05512819,
       -0.0688937 , -0.03679999, -0.00806454,  0.11615873,  0.01714965,
       -0.00665897,  0.08212683,  0.11267821, -0.06024361,  0.11026154,
       -0.01583233, -0.00263792, -0.02273386, -0.02976402,  0.02406186,
       -0.07536526, -0.03978354,  0.08828166, -0.01506544,  0.17

In [143]:
#Exercise
dice = np.random.choice([1,2,3,4,5,6],10)
dice

array([4, 6, 5, 1, 6, 3, 5, 5, 5, 2])

In [147]:
coin_toss = np.random.choice(['H','T'],10,p=[0.7,0.3])
coin_toss

array(['H', 'H', 'H', 'T', 'H', 'T', 'H', 'H', 'H', 'H'], dtype='<U1')